databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: postgresql://postgres.qacgiaqgsmmmazgobkzh:Hackathongas2024@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
        fromDatabase:
          name: Hackathon2024
          property: connectionString
      - key: qFCG6_oA-iZ6fOc8_U6nw7JVU771b7B8QyOtAI2-8Hk
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4