# Generated by Django 5.1.2 on 2024-10-25 18:46

import django.db.models.deletion
import hackathon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_cliente", models.CharField(max_length=45)),
                ("cnpj_cliente", models.CharField(max_length=14)),
                ("endereco_cliente", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endereco_estoque", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Ferramentaspecas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_ferramentaspecas", models.CharField(max_length=45)),
                ("valor_ferramentaspecas", models.CharField(max_length=5)),
                ("quantidade_ferramentaspecas", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagem", models.ImageField(upload_to="imagens/")),
            ],
        ),
        migrations.CreateModel(
            name="Paralelismo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("superioresquerdo_paralelismo", models.CharField(max_length=5)),
                ("superiordireito_paralelismo", models.CharField(max_length=5)),
                ("inferioresquerdo_paralelismo", models.CharField(max_length=5)),
                ("inferiordireito_paralelismo", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_servico", models.CharField(max_length=45)),
                ("tempo_Servico", models.TimeField()),
                ("orcamento_idorcamentos", models.IntegerField()),
                ("orcamentos_cliente_cnpjcliente", models.CharField(max_length=14)),
                ("orcamentos_cliente_idcliente", models.CharField(max_length=14)),
                ("nome_servico", models.CharField(max_length=45)),
                ("relatorio_id_relatorio", models.IntegerField()),
                ("relatorio_verificacoespreventivas_idverificacoespreventivas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=350)),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=128)),
                ("telefone", models.CharField(max_length=11, validators=[hackathon.models.only_numbers])),
            ],
        ),
        migrations.CreateModel(
            name="Verificacoespreventivas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paralelismo_idparalelismo", models.IntegerField()),
                ("estiramento_idestiramento", models.IntegerField()),
                ("limpezaequipamentos_verificacoespreventivas", models.IntegerField()),
                ("testesdemovimento_verificacoespreventivas", models.IntegerField()),
                ("seguranca_verificacoespreventivas", models.IntegerField()),
                ("funcionamentoalimentador_verificacoespreventivas", models.IntegerField()),
                ("funcionamentomanipulador_verificacoespreventivas", models.IntegerField()),
                ("ruidoaparelho_verificacoespreventivas", models.IntegerField()),
                ("aquecimentoconformeprog_verificacoespreventivas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Orcamentos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_orcamento", models.CharField(max_length=45)),
                ("datasolicitada_orcamento", models.DateField(blank=True, null=True)),
                ("valor_orcamento", models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ("tipo_orcamento", models.CharField(max_length=45, null=True)),
                (
                    "endereco_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="cliente", to="hackathon.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("matricula", models.CharField(max_length=10)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="funcionarios", to="hackathon.cargo"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="funcionario", to="hackathon.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrador",
                        to="hackathon.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_relatorio", models.CharField(max_length=45)),
                ("dificuldadeservico_relatorio", models.IntegerField()),
                ("colaboracaodaempresa_relatorio", models.IntegerField()),
                ("datainicialservico_relatorio", models.DateField()),
                ("datafinalservico_relatorio", models.DateField()),
                ("pendenciasmaquina_relatorio", models.CharField(max_length=45)),
                (
                    "Verificacoespreventivas_idverificacoespreventivas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="IDverificacoespreventivas",
                        to="hackathon.verificacoespreventivas",
                    ),
                ),
            ],
        ),
    ]
