# Generated by Django 5.1.2 on 2024-10-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamentos",
            name="datasolicitada_orcamento",
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name="orcamentos",
            name="valor_orcamento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
