# Generated by Django 5.1.2 on 2024-10-14 17:57

import django.db.models.deletion
import hackathon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0003_usuariodados_delete_funcionario"),
    ]

    operations = [
        migrations.CreateModel(
            name="usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("matricula", models.CharField(max_length=10)),
                ("endereco", models.CharField(max_length=350)),
                ("email", models.EmailField(max_length=254)),
                ("senha", models.CharField(max_length=20)),
                (
                    "telefone",
                    models.CharField(
                        max_length=11, validators=[hackathon.models.only_numbers]
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="funcionarios",
                        to="hackathon.cargo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="usuarioDados",
        ),
    ]
