# Generated by Django 5.1.2 on 2024-10-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0004_usuario_delete_usuariodados"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_cliente", models.CharField(max_length=45)),
                ("cnpj_cliente", models.CharField(max_length=14)),
                ("endereco_cliente", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endereco_estoque", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Ferramentaspecas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_ferramentaspecas", models.CharField(max_length=45)),
                ("valor_ferramentaspecas", models.CharField(max_length=5)),
                ("quantidade_ferramentaspecas", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Paralelismo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("superioresquerdo_paralelismo", models.CharField(max_length=5)),
                ("superiordireito_paralelismo", models.CharField(max_length=5)),
                ("inferioresquerdo_paralelismo", models.CharField(max_length=5)),
                ("inferiordireito_paralelismo", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Relatorio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_relatorio", models.CharField(max_length=45)),
                ("dificuldadeservico_relatorio", models.IntegerField()),
                ("colaboracaodaempresa_relatorio", models.IntegerField()),
                ("datainicialservico_relatorio", models.DateField()),
                ("datafinalservico_relatorio", models.DateField()),
                ("pendenciasmaquina_relatorio", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_servico", models.CharField(max_length=45)),
                ("tempo_Servico", models.TimeField()),
                ("orcamento_idorcamentos", models.IntegerField()),
                ("orcamentos_cliente_cnpjcliente", models.CharField(max_length=14)),
                ("orcamentos_cliente_idcliente", models.CharField(max_length=14)),
                ("nome_servico", models.CharField(max_length=45)),
                ("relatorio_id_relatorio", models.IntegerField()),
                ("relatorio_verificacoespreventivas_idverificacoespreventivas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Verificacoespreventivas",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paralelismo_idparalelismo", models.IntegerField()),
                ("estiramento_idestiramento", models.IntegerField()),
                ("limpezaequipamentos_verificacoespreventivas", models.IntegerField()),
                ("testesdemovimento_verificacoespreventivas", models.IntegerField()),
                ("seguranca_verificacoespreventivas", models.IntegerField()),
                ("funcionamentoalimentador_verificacoespreventivas", models.IntegerField()),
                ("funcionamentomanipulador_verificacoespreventivas", models.IntegerField()),
                ("ruidoaparelho_verificacoespreventivas", models.IntegerField()),
                ("aquecimentoconformeprog_verificacoespreventivas", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Orcamentos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descricao_orcamento", models.CharField(max_length=45)),
                ("cnpj_cliente", models.CharField(max_length=14)),
                ("endereco_cliente", models.CharField(max_length=45)),
                ("cliente", models.ManyToManyField(related_name="Orcamentos", to="hackathon.cliente")),
            ],
        ),
    ]
